/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_oceanwing_readscanlib_ReadScanNdkJniUtils */

#ifndef _Included_com_oceanwing_readscanlib_ReadScanNdkJniUtils
#define _Included_com_oceanwing_readscanlib_ReadScanNdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_oceanwing_readscanlib_ReadScanNdkJniUtils
 * Method:    select_eq
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_oceanwing_readscanlib_ReadScanNdkJniUtils_select_1eq
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
