/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_oceanwig_mylib_NdkJniUtils */

#ifndef _Included_com_oceanwig_mylib_NdkJniUtils
#define _Included_com_oceanwig_mylib_NdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_oceanwig_mylib_NdkJniUtils
 * Method:    getStringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_oceanwig_mylib_NdkJniUtils_getStringFromJni
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
